Continuous Deployment
NachoMemes/NachoMemes pull request #91
Opened 2021-03-16 06:06 UTC by jswny

Adds automatic deployment for the bot. 

- [ ] Update deploy condition to deploy on develop
- [ ] Update bot token to production token

2021-03-16 06:07 UTC, ironchefpython commented
No.  This needs to be ansible and a bunch of other stuff.

2021-03-16 06:07 UTC, jswny commented
Waiting on @samcat116 to give me a VM that isn't ARM. Other than that this should be good to go after that is done (just need to edit some temporary values).

2021-03-16 06:09 UTC, jswny commented
> No. This needs to be ansible and a bunch of other stuff.

Sam has my permission to nuke this as soon as he's done with his stuff 😎

2021-03-17 07:28 UTC, cooperpellaton requested changes

2021-03-17 07:28 UTC, cooperpellaton commented on .github/workflows/ci.yml
>            labels: ${{ steps.image-metadata.outpus.labels }}
Typo here. `outpus` -> `outputs`.

2021-03-17 15:14 UTC, jswny commented on .github/workflows/ci.yml
>            labels: ${{ steps.image-metadata.outpus.labels }}
Fixed, good catch!

2021-03-17 20:52 UTC, ironchefpython approved these changes
This is all stupid and pointless when you can just use python to run it.

Approved.

2021-03-17 20:53 UTC, jswny commented
> This is all stupid and pointless when you can just use python to run it.
> 
> Approved.

I'll believe it when I see it ;)

2021-03-17 20:54 UTC, ironchefpython commented
`/usr/bin/python3.9 -m poetry run python -m nachomemes.bot`

Checkmate Atheist

2021-03-17 20:55 UTC, jswny commented
> `/usr/bin/python3.9 -m poetry run python -m nachomemes.bot`
> 
> Checkmate Atheist

This is a human rights violation

2021-03-17 20:56 UTC, ironchefpython commented
\*beep-boop\* 

The robot overlords care not for your rights.

2021-03-18 07:36 UTC, merged